name: FoodExpiration
version: ${version}
main: com.leonardobishop.foodexpiration.FoodExpirationPlugin
author: LMBishop
api-version: "1.16"

commands:
  foodexpiration:
    description: "Main command for FoodExpiration"
    permission: foodexpiration.command

permissions:
  foodexpiration.command:
    description: "Access main command for FoodExpiration"
